"""Generate a C header from the deliberately restricted current Rust C ABI.

Only repr(C) structs, integer constants and exported C functions are supported.
Unsupported declarations fail closed; this is not a general Rust binding tool.
"""
from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path


PRIMITIVES = {"u8": "uint8_t", "u32": "uint32_t", "u64": "uint64_t",
              "i32": "int32_t", "i64": "int64_t", "usize": "size_t", "()": "void"}


def integer(expression: str) -> int:
    def visit(node: ast.AST) -> int:
        if isinstance(node, ast.Constant) and type(node.value) is int:
            return node.value
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Mult):
            return visit(node.left) * visit(node.right)
        raise ValueError("unsupported ABI constant expression")
    try:
        expression_ast = ast.parse(expression, mode="eval").body
    except SyntaxError as error:
        raise ValueError("unsupported ABI constant expression") from error
    value = visit(expression_ast)
    if not 0 <= value <= 0xFFFFFFFF:
        raise ValueError("ABI constant exceeds uint32")
    return value


def generate(foundation: str, product: str, guard: str) -> str:
    if not re.fullmatch(r"[A-Z][A-Z0-9_]*_H", guard):
        raise ValueError("invalid C include guard")
    sources = [foundation, product]
    structs = []
    for source in sources:
        structs.extend(re.findall(r"#\[repr\(C\)\]\s*pub struct (\w+)\s*\{([^}]+)\}", source))
    names = {name for name, _ in structs}
    if len(names) != len(structs):
        raise ValueError("duplicate ABI structure")

    def ctype(value: str) -> str:
        value = value.strip()
        if value.startswith("*const "):
            return "const " + ctype(value[7:]) + " *"
        if value.startswith("*mut "):
            return ctype(value[5:]) + " *"
        if value in PRIMITIVES:
            return PRIMITIVES[value]
        if value in names:
            return value
        raise ValueError(f"unsupported ABI type: {value}")

    lines = ["/* Generated by Foundation tools/ffi_header.py; do not edit. */",
             f"#ifndef {guard}", f"#define {guard}", "#include <stddef.h>",
             "#include <stdint.h>", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    constants = re.findall(r"^pub const (\w+): (?:u32|i32|usize) = ([^;]+);", foundation, re.M)
    if not constants:
        raise ValueError("missing Foundation ABI constants")
    for name, value in constants:
        if not name.startswith("SARMG_FFI_"):
            name = "SARMG_FFI_" + name
        lines.append(f"#define {name} {integer(value)}u")
    lines.append("")
    for name, body in structs:
        lines.append(f"typedef struct {name} {{")
        for field in body.split(","):
            if not field.strip():
                continue
            match = re.fullmatch(r"\s*pub (\w+)\s*:\s*(.+)\s*", field, re.S)
            if match is None:
                raise ValueError(f"unsupported field in {name}")
            field_name, field_type = match.groups()
            lines.append(f"    {ctype(field_type)} {field_name};")
        lines.append(f"}} {name};")
    lines += ["", "/* Inputs are borrowed for the call. Output must be aligned, writable, and",
              " * not alias input or contain an unreleased result. Status is authoritative.",
              " * Free each result in its original storage with sarmg_ffi_result_free_v2;",
              " * do not copy, modify, or separately free its pointer/length pair. */"]
    exports = set()
    pattern = re.compile(r'pub (?:unsafe )?extern "C" fn (\w+)\s*\(([^)]*)\)\s*(?:->\s*([^\{]+))?\{', re.S)
    for source in sources:
        functions = list(pattern.finditer(source))
        if len(functions) != len(re.findall(r'pub (?:unsafe )?extern "C" fn', source)):
            raise ValueError("unsupported exported function declaration")
        for match in functions:
            name, arguments, result = match.groups()
            if name in exports:
                raise ValueError("duplicate C export")
            exports.add(name)
            parameters = []
            for argument in arguments.split(","):
                if not argument.strip():
                    continue
                field, kind = argument.strip().split(":", 1)
                if not re.fullmatch(r"[a-z][a-z0-9_]*", field):
                    raise ValueError("invalid C parameter")
                parameters.append(f"{ctype(kind)} {field}")
            lines.append(f"{ctype(result or '()')} {name}({', '.join(parameters) or 'void'});")
    if not exports:
        raise ValueError("missing C exports")
    lines += ["", "#ifdef __cplusplus", "}", "#endif", f"#endif /* {guard} */", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--product-source", type=Path, required=True)
    parser.add_argument("--guard", required=True)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    source = Path(__file__).resolve().parents[1] / "rust/crates/sarmg-mobile-ffi/src/lib.rs"
    generated = generate(source.read_text(), args.product_source.read_text(), args.guard)
    if args.check:
        if args.check.read_text() != generated:
            raise SystemExit("current C header differs from the Rust ABI")
    else:
        print(generated, end="")


if __name__ == "__main__":
    main()
